# Generated by Django 6.0.1 on 2026-02-10 14:07

import users_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users_app.models.CustomUserManager()),
            ],
        ),
    ]
